### ISSUE TITLE
Is Apache spark integration available?

### ISSUE THREAD

**Issue by Jiakui** [SkymindIO/deeplearning4j#125]
On maven repository I saw Apache-spark integration for Deeplearning4j. 
http://search.maven.org/#search%7Cga%7C1%7Cdeeplearning4j

Does this means we can use apache spark together with deeplearning4j?

Thanks!

**Comment by agibsonccc** [comment]
Yes we have an early technology preview. Here's an example: https://github.com/SkymindIO/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/spark-cdh5/src/test/java/org/deeplearning4j/spark/impl/multilayer/TestMaster.java

Because of the way we have built deep learning4j, this also allows you to say: switch in a cuda backend for running GPUs on spark.

**Comment by agibsonccc** [comment]
Look at spark-cdh5.
